=== Maintenance Mode

This project is in maintenance mode and https://spring.io/blog/2020/09/22/spring-security-saml-extensions-1-x-eol-on-october-6-2021[will each End-of-Life on 6 October 2021]. Please use https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-saml2[Spring Security's SAML support] instead.

NOTE: In the past, there were `develop` and `develop-3.0` branches, though these are not maintained, and PRs are no longer being considered on these branches.
No further releases will be issued from these two branches.
Please feel free to fork the repository if you need to make changes.

We continue to consider pull requests for 1.0.x bug fixes, but are not actively developing this project.

image:https://badges.gitter.im/Join%20Chat.svg[Gitter,link=https://gitter.im/spring-projects/spring-security?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge]

image:https://travis-ci.org/spring-projects/spring-security-saml.svg?branch=master["Build Status", link="https://travis-ci.org/spring-projects/spring-security-saml"]

= Spring SAML

Spring SAML Extension allows seamless inclusion of SAML 2.0 Service Provider capabilities in Spring applications.
All products supporting SAML 2.0 in Identity Provider mode (e.g. ADFS 2.0, Shibboleth, OpenAM/OpenSSO, Ping Federate, Okta) can be used to connect with Spring SAML Extension.

For a detailed list of features and access to the latest release, please visit https://projects.spring.io/spring-security-saml/[Spring projects].

== Code of Conduct
Please see our https://github.com/spring-projects/.github/blob/master/CODE_OF_CONDUCT.md[code of conduct].

== Dependencies

Spring Security SAML publishes GA (general availability) versions to https://search.maven.org[Maven Central], so you can just add the following to your POM:

[source,xml]
----
<dependency>
    <groupId>org.springframework.security.extensions</groupId>
    <artifactId>spring-security-saml</artifactId>
    <version>1.0.10.RELEASE</version>
</dependency>
----

or the following to `build.gradle`:

[source,gradle]
----
implementation 'org.springframework.security.extensions:spring-security-saml:1.0.10.RELEASE'
----

See https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Artifacts[downloading Spring artifacts] for more information.

== Documentation

Be sure to read the https://docs.spring.io/spring-security-saml/docs/current/reference/htmlsingle[Spring Security SAML Reference].
JavaDoc is also available in https://docs.spring.io/spring-security-saml/docs/current/api[the Spring Security API Documentation].

== Quick Start

We recommend you visit https://docs.spring.io/spring-security-saml/docs/current/reference/htmlsingle/#chapter-quick-start[Spring Security SAML Reference's quick start].

Or, feel free to check out https://saml-federation.appspot.com/[an online demonstration].

== Building from Source
Spring Security SAML uses a https://gradle.org[Gradle]-based build system.
In the instructions below, https://vimeo.com/34436402[./gradlew] is invoked from the root of the source tree and serves as a cross-platform, self-contained bootstrap mechanism for the build.

=== Prerequisites
https://help.github.com/set-up-git-redirect[Git] and a https://www.oracle.com/technetwork/java/javase/downloads[JDK], Spring Security SAML is compatible with JDK 1.6.

Be sure that your `JAVA_HOME` environment variable points to the JDK folder extracted from the download.

=== Checkout sources
[indent=0]
----
git clone git@github.com:spring-projects/spring-security-saml.git
----

=== Install all spring-\* jars into your local Maven cache
[indent=0]
----
./gradlew install
----

=== Compile and test; build all jars, distribution zips, and docs
[indent=0]
----
./gradlew build
----

Discover more commands with `./gradlew tasks`.
See also Spring Framework's https://github.com/spring-projects/spring-framework/wiki/Build-from-Source[Build from Source] documentation.

== Getting Support
Check out the https://stackoverflow.com/questions/tagged/spring-saml[Spring Security SAML tag on Stack Overflow].
https://spring.io/services[Commercial support] is available too.

Commercial: vladimir@v7security.com

== Contributing
https://help.github.com/articles/creating-a-pull-request[Pull requests] are welcome; see the https://github.com/spring-projects/spring-security-saml/blob/master/CONTRIBUTING.md[contributor guidelines] for details.
