= Spring SAML

image:https://travis-ci.org/spring-projects/spring-security-saml.svg?branch=master["Build Status", link="https://travis-ci.org/spring-projects/spring-security-saml"]

== Upgrade note

This project is being rewritten in https://github.com/spring-projects/spring-security[Spring Security]. As such, https://github.com/spring-projects/spring-security/issues/new[new feature requests] should be logged there.

In the past, there were `develop` and `develop-3.0` branches, though these are not maintained, and PRs are no longer being considered on these branches. No further releases will be issued from these two branches. Please feel free to fork the repository if you need to make changes.

We continue to consider pull requests for the 1.0.x branch, but are not actively developing it.

== Introduction

Spring SAML Extension allows seamless inclusion of SAML 2.0 Service Provider capabilities in Spring applications. All products supporting SAML 2.0 in Identity Provider mode (e.g. ADFS 2.0, Shibboleth, OpenAM/OpenSSO, Ping Federate, Okta) can be used to connect with Spring SAML Extension.

== Code of Conduct
This project adheres to the Contributor Covenant https://github.com/spring-projects/spring-security-saml/blob/master/CODE_OF_CONDUCT.adoc[code of conduct].
By participating, you are expected to uphold this code. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.

== Links
Web:
https://projects.spring.io/spring-security-saml/

Sources: https://github.com/spring-projects/spring-security-saml
Documentation: https://docs.spring.io/spring-security-saml/docs/1.0.x-SNAPSHOT/reference/
Jira: https://jira.spring.io/browse/SES/component/10711/
CI: https://build.springsource.org/browse/SES

Releases:
Final: https://repo.spring.io/list/release/org/springframework/security/extensions/
Milestone: https://repo.spring.io/list/milestone/org/springframework/security/extensions/
Snapshot: https://repo.spring.io/list/snapshot/org/springframework/security/extensions/

Support:
Stackoverflow: https://stackoverflow.com/questions/tagged/spring-saml
Forum: https://forum.spring.io/forum/spring-projects/security/saml
Commercial: vladimir@v7security.com

Online demo: https://saml-federation.appspot.com/
